const CLEAR_ALERT = 'CLEAR_ALERT';
const SET_REQUEST_PENDING = 'SET_REQUEST_PENDING';
const SET_ALERT = 'SET_ALERT';
const SET_AUTH = 'SET_AUTH';
const REMOVE_AUTH = 'REMOVE_AUTH';
const HANDLE_NOTIFICATION = 'HANDLE_NOTIFICATION';

export default {
  CLEAR_ALERT,
  SET_ALERT,
  SET_REQUEST_PENDING,
  SET_AUTH,
  REMOVE_AUTH,
  HANDLE_NOTIFICATION,
};
